// dEDI_react/src/components/heading.js
import React from 'react'

import PropTypes from 'prop-types'

import projectStyles from '../style.module.css'
import styles from './heading.module.css'

const Heading = (props) => {
  return (
    <div className={styles['container']}>
      <img
        alt="image"
        src="https://aheioqhobo.cloudimg.io/v7/_playground-bucket.teleporthq.io_/03d14fbb1e2aa53317ceb7d1e6be7560"
        className={styles['image']}
      />
      <h1 className={` ${styles['text']} ${projectStyles['heading']} `}>
        {props.heading1}
      </h1>
      <span className={` ${styles['text1']} ${projectStyles['subheading']} `}>
        {props.text}
      </span>
    </div>
  )
}

Heading.defaultProps = {
  heading1: 'Heading',
  text: 'Let’s walk through this tutorial together to get you ready for building your next projects',
}

Heading.propTypes = {
  heading1: PropTypes.string,
  text: PropTypes.string,
}

export default Heading

// dEDI_nuxt/components/heading.vue
<template>
  <div class="heading-container">
    <img
      alt="image"
      src="https://aheioqhobo.cloudimg.io/v7/_playground-bucket.teleporthq.io_/03d14fbb1e2aa53317ceb7d1e6be7560"
      class="heading-image"
    />
    <h1 class="heading-text heading">{{ heading1 }}</h1>
    <span class="heading-text1 subheading">{{ text }}</span>
  </div>
</template>

<script>
export default {
  name: 'Heading',
  props: {
    heading1: {
      type: String,
      default: 'Heading',
    },
    text: {
      type: String,
      default:
        'Let’s walk through this tutorial together to get you ready for building your next projects',
    },
  },
}
</script>

<style scoped>
.heading-container {
  display: flex;
  max-width: 600px;
  margin-top: var(--dl-space-space-tripleunit);
  align-items: flex-start;
  margin-bottom: var(--dl-space-space-doubleunit);
  flex-direction: column;
  justify-content: flex-start;
}
.heading-image {
  width: 150px;
  object-fit: cover;
  margin-bottom: var(--dl-space-space-doubleunit);
}
.heading-text {
  width: 100%;
  text-align: left;
  margin-bottom: var(--dl-space-space-halfunit);
}
.heading-text1 {
  text-align: left;
}
</style>
