// dEDI_stencil/src/components/navbar/index.tsx
import { Component, h, Prop } from '@stencil/core'

@Component({
  tag: 'app-navbar',
  shadow: true,
  styleUrls: ['style.css'],
})
export class Navbar {
  @Prop()
  text7: string = 'Inventory'
  @Prop()
  text: string = 'Dashboard'
  @Prop()
  text3: string = 'Forms'
  @Prop()
  text4: string = 'Messaging'
  @Prop()
  text2: string = 'Received'
  @Prop()
  text1: string = 'Sent'
  @Prop()
  text6: string = 'Tracking'
  @Prop()
  text8: string = 'Financial'
  @Prop()
  rootClassName: string = ''
  @Prop()
  text5: string = 'Partners'

  render() {
    return (
      <nav id="sidebar" class={`container ${this.rootClassName} `}>
        <span id="dash_link" class="text">
          {this.text}
        </span>
        <span id="sent_link" class="text1">
          {this.text1}
        </span>
        <span id="recv_link" class="text2">
          {this.text2}
        </span>
        <span id="forms_link" class="text3">
          {this.text3}
        </span>
        <span id="msg_link" class="text4">
          {this.text4}
        </span>
        <span id="partners_link" class="text5">
          {this.text5}
        </span>
        <span id="tracking_link" class="text6">
          {this.text6}
        </span>
        <span id="inventory_link" class="text7">
          {this.text7}
        </span>
        <span id="financial_link" class="text8">
          {this.text8}
        </span>
      </nav>
    )
  }
}

// dEDI_angular/src/app/components/navbar/navbar.component.ts
import { Component, Input } from '@angular/core'

@Component({
  selector: 'app-navbar',
  templateUrl: 'navbar.component.html',
  styleUrls: ['navbar.component.css'],
})
export class Navbar {
  @Input()
  text7: string = 'Inventory'
  @Input()
  text: string = 'Dashboard'
  @Input()
  text3: string = 'Forms'
  @Input()
  text4: string = 'Messaging'
  @Input()
  text2: string = 'Received'
  @Input()
  text1: string = 'Sent'
  @Input()
  text6: string = 'Tracking'
  @Input()
  text8: string = 'Financial'
  @Input()
  rootClassName: string = ''
  @Input()
  text5: string = 'Partners'

  constructor() {}
}

<nav id="sidebar" class="container" [ngClass]="rootClassName">
  <span id="dash_link" class="text">{{ text }}</span>
  <span id="sent_link" class="text1">{{ text1 }}</span>
  <span id="recv_link" class="text2">{{ text2 }}</span>
  <span id="forms_link" class="text3">{{ text3 }}</span>
  <span id="msg_link" class="text4">{{ text4 }}</span>
  <span id="partners_link" class="text5">{{ text5 }}</span>
  <span id="tracking_link" class="text6">{{ text6 }}</span>
  <span id="inventory_link" class="text7">{{ text7 }}</span>
  <span id="financial_link" class="text8">{{ text8 }}</span>
</nav>
