// dEDI_react/src/components/navbar.js
import React from 'react'

import PropTypes from 'prop-types'

import styles from './navbar.module.css'

const Navbar = (props) => {
  return (
    <nav
      id="sidebar"
      className={` ${styles['container']} ${styles[props.rootClassName]} `}
    >
      <span id="dash_link" className={styles['text']}>
        {props.text}
      </span>
      <span id="sent_link" className={styles['text1']}>
        {props.text1}
      </span>
      <span id="recv_link" className={styles['text2']}>
        {props.text2}
      </span>
      <span id="forms_link" className={styles['text3']}>
        {props.text3}
      </span>
      <span id="msg_link" className={styles['text4']}>
        {props.text4}
      </span>
      <span id="partners_link" className={styles['text5']}>
        {props.text5}
      </span>
      <span id="tracking_link" className={styles['text6']}>
        {props.text6}
      </span>
      <span id="inventory_link" className={styles['text7']}>
        {props.text7}
      </span>
      <span id="financial_link" className={styles['text8']}>
        {props.text8}
      </span>
    </nav>
  )
}

Navbar.defaultProps = {
  text7: 'Inventory',
  text: 'Dashboard',
  text3: 'Forms',
  text4: 'Messaging',
  text2: 'Received',
  text1: 'Sent',
  text6: 'Tracking',
  text8: 'Financial',
  rootClassName: '',
  text5: 'Partners',
}

Navbar.propTypes = {
  text7: PropTypes.string,
  text: PropTypes.string,
  text3: PropTypes.string,
  text4: PropTypes.string,
  text2: PropTypes.string,
  text1: PropTypes.string,
  text6: PropTypes.string,
  text8: PropTypes.string,
  rootClassName: PropTypes.string,
  text5: PropTypes.string,
}

export default Navbar

// dEDI_stencil/src/components/navbar/index.tsx
import { Component, h, Prop } from '@stencil/core'

@Component({
  tag: 'app-navbar',
  shadow: true,
  styleUrls: ['style.css'],
})
export class Navbar {
  @Prop()
  text7: string = 'Inventory'
  @Prop()
  text: string = 'Dashboard'
  @Prop()
  text3: string = 'Forms'
  @Prop()
  text4: string = 'Messaging'
  @Prop()
  text2: string = 'Received'
  @Prop()
  text1: string = 'Sent'
  @Prop()
  text6: string = 'Tracking'
  @Prop()
  text8: string = 'Financial'
  @Prop()
  rootClassName: string = ''
  @Prop()
  text5: string = 'Partners'

  render() {
    return (
      <nav id="sidebar" class={`container ${this.rootClassName} `}>
        <span id="dash_link" class="text">
          {this.text}
        </span>
        <span id="sent_link" class="text1">
          {this.text1}
        </span>
        <span id="recv_link" class="text2">
          {this.text2}
        </span>
        <span id="forms_link" class="text3">
          {this.text3}
        </span>
        <span id="msg_link" class="text4">
          {this.text4}
        </span>
        <span id="partners_link" class="text5">
          {this.text5}
        </span>
        <span id="tracking_link" class="text6">
          {this.text6}
        </span>
        <span id="inventory_link" class="text7">
          {this.text7}
        </span>
        <span id="financial_link" class="text8">
          {this.text8}
        </span>
      </nav>
    )
  }
}
