// dEDI_react/src/views/login.js
import React from 'react'
import { Link } from 'react-router-dom'

import { Helmet } from 'react-helmet'

import projectStyles from '../style.module.css'
import styles from './login.module.css'

const Login = () => {
  return (
    <div className={styles['container']}>
      <Helmet>
        <title>dEDI Icn</title>
        <meta property="og:title" content="dEDI Icn" />
      </Helmet>
      <div id="login_container" className={styles['container1']}>
        <div id="login_body" className={styles['body']}>
          <div id="login_footer" className={styles['footer']}>
            <span id="login_footer_copy" className={styles['copyright']}>
              © 2021 dEDI Incorporated
            </span>
            <img
              id="login_footer_logo"
              alt="image"
              src="/playground_assets/dedi_logo_trans-1000h.png"
              className={styles['image']}
            />
          </div>
          <div id="login_header" className={styles['header']}>
            <img
              id="login_header_logo"
              alt="dEDI logo"
              src="/playground_assets/dedi_logo_trans-1000h.png"
              className={styles['logo']}
            />
          </div>
          <div id="login_main" className={styles['main']}>
            <div id="login_form" className={styles['container2']}>
              <input
                type="email"
                id="login_user_id_login"
                name="Username"
                required="true"
                placeholder="Username"
                autoComplete="on"
                className={` ${styles['username']} ${projectStyles['thqTextInput']} `}
              />
              <input
                type="password"
                id="login_password"
                name="Password"
                required="true"
                placeholder="Password"
                autoComplete="on"
                className={` ${styles['password']} ${projectStyles['thqTextInput']} `}
              />
              <div
                id="login_buttons_container"
                className={styles['container3']}
              >
                <Link
                  to="/dashboard"
                  id="login_login_button"
                  name="Login"
                  type="submit"
                  className={` ${styles['loginbutton']} ${projectStyles['thqButton']} ${projectStyles['thqLink']} `}
                >
                  Login
                </Link>
                <Link
                  to="/create_user"
                  id="login_help_button"
                  name="Help"
                  type="Link"
                  className={` ${styles['helpbutton']} ${projectStyles['thqButton']} ${projectStyles['thqLink']} `}
                >
                  <span id="login_create_acct">signup</span>
                  <br></br>
                </Link>
              </div>
              <span id="login_forgot_pass" className={styles['text2']}>
                <span className={styles['text3']}>Forgot Password</span>
              </span>
              <Link
                to="/create_org"
                id="login_new_org_link"
                className={` ${styles['navlink']} ${projectStyles['thqLink']} `}
              >
                New Organizatiion Signup
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Login

// dEDI_angular/src/app/pages/login/login.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'app-login',
  templateUrl: 'login.component.html',
  styleUrls: ['login.component.css'],
})
export class Login {
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('dEDI Icn')
    this.meta.addTags([
      {
        property: 'og:title',
        content: 'dEDI Icn',
      },
    ])
  }
}

<div class="container">
  <div id="login_container" class="container1">
    <div id="login_body" class="body">
      <div id="login_footer" class="footer">
        <span id="login_footer_copy" class="copyright">
          © 2021 dEDI Incorporated
        </span>
        <img
          id="login_footer_logo"
          alt="image"
          src="/assets/playground_assets/dedi_logo_trans-1000h.png"
          class="image"
        />
      </div>
      <div id="login_header" class="header">
        <img
          id="login_header_logo"
          alt="dEDI logo"
          src="/assets/playground_assets/dedi_logo_trans-1000h.png"
          class="logo"
        />
      </div>
      <div id="login_main" class="main">
        <div id="login_form" class="container2">
          <input
            type="email"
            id="login_user_id_login"
            name="Username"
            required="true"
            placeholder="Username"
            autocomplete="on"
            class="username thqTextInput"
          />
          <input
            type="password"
            id="login_password"
            name="Password"
            required="true"
            placeholder="Password"
            autocomplete="on"
            class="password thqTextInput"
          />
          <div id="login_buttons_container" class="container3">
            <a
              id="login_login_button"
              name="Login"
              type="submit"
              transitionTo="/dashboard"
              class="loginbutton thqButton thqLink"
            >
              Login
            </a>
            <a
              id="login_help_button"
              name="Help"
              type="Link"
              transitionTo="/create_user"
              class="helpbutton thqButton thqLink"
            >
              <span id="login_create_acct">signup</span>
              <br />
            </a>
          </div>
          <span id="login_forgot_pass" class="text2">
            <span class="text3">Forgot Password</span>
          </span>
          <a
            id="login_new_org_link"
            transitionTo="/create_org"
            class="navlink thqLink"
          >
            New Organizatiion Signup
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
