// dEDI_stencil/src/components/component5/index.tsx
import { Component, h, Prop } from '@stencil/core'

@Component({
  tag: 'app-component5',
  shadow: true,
  styleUrls: ['style.css'],
})
export class Component5 {
  @Prop()
  image_src: string = '/playground_assets/dedi_logo_trans-1000h.png'
  @Prop()
  image_alt: string = 'image'

  render() {
    return (
      <div class="container">
        <img alt={this.image_alt} src={this.image_src} class="image" />
      </div>
    )
  }
}

// dEDI_angular/src/app/components/component5/component5.component.ts
import { Component, Input } from '@angular/core'

@Component({
  selector: 'app-component5',
  templateUrl: 'component5.component.html',
  styleUrls: ['component5.component.css'],
})
export class Component5 {
  @Input()
  image_src: string = '/playground_assets/dedi_logo_trans-1000h.png'
  @Input()
  image_alt: string = 'image'

  constructor() {}
}

<div class="container">
  <img [attr.alt]="image_alt" [attr.src]="image_src" class="image" />
</div>
