// dEDI_stencil/src/components/buttom/index.tsx
import { Component, h, Prop } from '@stencil/core'

@Component({
  tag: 'app-buttom',
  shadow: true,
  styleUrls: ['style.css'],
})
export class Buttom {
  @Prop()
  loginbutton: string = 'Login'
  @Prop()
  rootClassName: string = ''

  render() {
    return (
      <div class={`container ${this.rootClassName} `}>
        <button
          id="login_button"
          name="Login"
          type="submit"
          class="loginbutton thqButton"
        >
          {this.loginbutton}
        </button>
      </div>
    )
  }
}

// dEDI_angular/src/app/components/buttom/buttom.component.ts
import { Component, Input } from '@angular/core'

@Component({
  selector: 'app-buttom',
  templateUrl: 'buttom.component.html',
  styleUrls: ['buttom.component.css'],
})
export class Buttom {
  @Input()
  loginbutton: string = 'Login'
  @Input()
  rootClassName: string = ''

  constructor() {}
}

<div class="container" [ngClass]="rootClassName">
  <button
    id="login_button"
    name="Login"
    type="submit"
    class="loginbutton thqButton"
  >
    {{ loginbutton }}
  </button>
</div>
