// dEDI_stencil/src/components/component5/index.tsx
import { Component, h, Prop } from '@stencil/core'

@Component({
  tag: 'app-component5',
  shadow: true,
  styleUrls: ['style.css'],
})
export class Component5 {
  @Prop()
  image_src: string = '/playground_assets/dedi_logo_trans-1000h.png'
  @Prop()
  image_alt: string = 'image'

  render() {
    return (
      <div class="container">
        <img alt={this.image_alt} src={this.image_src} class="image" />
      </div>
    )
  }
}

// dEDI_react/src/components/component5.js
import React from 'react'

import PropTypes from 'prop-types'

import styles from './component5.module.css'

const Component5 = (props) => {
  return (
    <div className={styles['container']}>
      <img
        alt={props.image_alt}
        src={props.image_src}
        className={styles['image']}
      />
    </div>
  )
}

Component5.defaultProps = {
  image_src: '/playground_assets/dedi_logo_trans-1000h.png',
  image_alt: 'image',
}

Component5.propTypes = {
  image_src: PropTypes.string,
  image_alt: PropTypes.string,
}

export default Component5
