// dEDI_stencil/src/components/heading/index.tsx
import { Component, h, Prop } from '@stencil/core'

@Component({
  tag: 'app-heading',
  shadow: true,
  styleUrls: ['style.css'],
})
export class Heading {
  @Prop()
  heading1: string = 'Heading'
  @Prop()
  text: string =
    'Let’s walk through this tutorial together to get you ready for building your next projects'

  render() {
    return (
      <div class="container">
        <img
          alt="image"
          src="https://aheioqhobo.cloudimg.io/v7/_playground-bucket.teleporthq.io_/03d14fbb1e2aa53317ceb7d1e6be7560"
          class="image"
        />
        <h1 class="text heading">{this.heading1}</h1>
        <span class="text1 subheading">{this.text}</span>
      </div>
    )
  }
}

// dEDI_react/src/components/heading.js
import React from 'react'

import PropTypes from 'prop-types'

import projectStyles from '../style.module.css'
import styles from './heading.module.css'

const Heading = (props) => {
  return (
    <div className={styles['container']}>
      <img
        alt="image"
        src="https://aheioqhobo.cloudimg.io/v7/_playground-bucket.teleporthq.io_/03d14fbb1e2aa53317ceb7d1e6be7560"
        className={styles['image']}
      />
      <h1 className={` ${styles['text']} ${projectStyles['heading']} `}>
        {props.heading1}
      </h1>
      <span className={` ${styles['text1']} ${projectStyles['subheading']} `}>
        {props.text}
      </span>
    </div>
  )
}

Heading.defaultProps = {
  heading1: 'Heading',
  text: 'Let’s walk through this tutorial together to get you ready for building your next projects',
}

Heading.propTypes = {
  heading1: PropTypes.string,
  text: PropTypes.string,
}

export default Heading
