// dEDI_stencil/src/components/component11/index.tsx
import { Component, h, Prop } from '@stencil/core'

@Component({
  tag: 'app-component11',
  shadow: true,
  styleUrls: ['style.css'],
})
export class Component11 {
  @Prop()
  link_dashboard: string = 'https://example.com'

  render() {
    return (
      <div class="container">
        <svg viewBox="0 0 1024 1024" class="icon">
          <path
            d="M726 726v-172h84v256h-512v128l-170-170 170-170v128h428zM298 298v172h-84v-256h512v-128l170 170-170 170v-128h-428z"
            class=""
          ></path>
        </svg>
        <a
          href={this.link_dashboard}
          target="_blank"
          rel="noreferrer noopener"
          class="dashboard thqLink"
        >
          <span class="">Working</span>
        </a>
      </div>
    )
  }
}

// dEDI_angular/src/app/components/component11/component11.component.ts
import { Component, Input } from '@angular/core'

@Component({
  selector: 'app-component11',
  templateUrl: 'component11.component.html',
  styleUrls: ['component11.component.css'],
})
export class Component11 {
  @Input()
  link_dashboard: string = 'https://example.com'

  constructor() {}
}

<div class="container">
  <svg viewBox="0 0 1024 1024" class="icon">
    <path
      d="M726 726v-172h84v256h-512v128l-170-170 170-170v128h428zM298 298v172h-84v-256h512v-128l170 170-170 170v-128h-428z"
    ></path>
  </svg>
  <a
    [attr.href]="link_dashboard"
    target="_blank"
    rel="noreferrer noopener"
    class="dashboard thqLink"
  >
    <span>Working</span>
  </a>
</div>
